"""
Public API NodeJS repositories, plus some legacy cruft that `yarn_install` needs.
"""

load("//lib/private:utils/strings.bzl", "dedent")

visibility(["//lib/private"])

def _nodejs_host_alias_impl(repository_ctx):
    # Base BUILD file for this repository
    repository_ctx.file(
        "BUILD.bazel",
        content = "",
    )

    # toolchain declarations (here to avoid eager downloading)
    repository_ctx.file(
        "toolchains/BUILD.bazel",
        content = dedent("""
            # Generated by node_repositories.bzl
            toolchain(
                name = "node_linux_amd64_toolchain",
                target_compatible_with = [
                    "@platforms//os:linux",
                    "@platforms//cpu:x86_64",
                ],
                toolchain = "@nodejs_linux_amd64_config//:toolchain",
                toolchain_type = "@build_bazel_rules_nodejs//lib:nodejs_toolchain_type",
            )

            toolchain(
                name = "node_linux_arm64_toolchain",
                target_compatible_with = [
                    "@platforms//os:linux",
                    "@platforms//cpu:aarch64",
                ],
                toolchain = "@nodejs_linux_arm64_config//:toolchain",
                toolchain_type = "@build_bazel_rules_nodejs//lib:nodejs_toolchain_type",
            )

            toolchain(
                name = "node_darwin_amd64_toolchain",
                target_compatible_with = [
                    "@platforms//os:osx",
                    "@platforms//cpu:x86_64",
                ],
                toolchain = "@nodejs_darwin_amd64_config//:toolchain",
                toolchain_type = "@build_bazel_rules_nodejs//lib:nodejs_toolchain_type",
            )

            toolchain(
                name = "node_darwin_arm64_toolchain",
                target_compatible_with = [
                    "@platforms//os:osx",
                    "@platforms//cpu:aarch64",
                ],
                toolchain = "@nodejs_darwin_arm64_config//:toolchain",
                toolchain_type = "@build_bazel_rules_nodejs//lib:nodejs_toolchain_type",
            )

            toolchain(
                name = "node_windows_amd64_toolchain",
                target_compatible_with = [
                    "@platforms//os:windows",
                    "@platforms//cpu:x86_64",
                ],
                toolchain = "@nodejs_windows_amd64_config//:toolchain",
                toolchain_type = "@build_bazel_rules_nodejs//lib:nodejs_toolchain_type",
            )

            toolchain(
                name = "node_linux_s390x_toolchain",
                target_compatible_with = [
                    "@platforms//os:linux",
                    "@platforms//cpu:s390x",
                ],
                toolchain = "@nodejs_linux_s390x_config//:toolchain",
                toolchain_type = "@build_bazel_rules_nodejs//lib:nodejs_toolchain_type",
            )
        """),
    )

nodejs_host_alias = repository_rule(
    _nodejs_host_alias_impl,
    attrs = {"node_version": attr.string()},
)
