name: Continuous Integration
on:
  # Main branch updated
  push:
    #branches:
    #  - main
  # Pull request
  pull_request:
    types:
      # Newly opened
      - opened
      # Updated (excludes change of base branch)
      - synchronize

jobs:
  test:
    # Development of ruleset proper only supported on macOS and Linux
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: bazel-test-${{ matrix.platform }}
    - run: bazel test //...
  e2e:
    strategy:
      matrix:
        scenario:
        - bazel_6_litmus
        - bazel_6_litmus_workspace
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    # Disabled for now pending completion of configuration
    # - name: Mount bazel cache
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/bazel
    #     key: bazel-e2e-${{ matrix.scenario }}-${{ matrix.platform }}
    - run: bazel test //...
      working-directory: e2e/${{ matrix.scenario }}

